services:
  ssh:
    security_opt: # options needed for gdb debugging
      - seccomp:unconfined
      - apparmor:unconfined
    cap_add:
      - SYS_PTRACE
    container_name: cpp_dev_env
    image: cpp_dev_env:latest
    environment:
        - TERM=xterm-256color # For a colored Terminal
        - SSH_AUTH_SOCK=/ssh-agent
    volumes:
        - ${PWD}/../:/home/dev/workspace
    command: /usr/sbin/sshd -D
    user: root
    network_mode: "bridge"
    ports:
      - "2222:22"
    privileged: true
    hostname: cpp_docker_env
