FUNCTION(ENABLE_IPO)
    IF(ENABLE_IPO)
        INCLUDE(CheckIPOSupported)
        CHECK_IPO_SUPPORTED(RESULT result OUTPUT output)
        IF(result)
            SET(CMAKE_INTERPROCEDURAL_OPTIMIZATION ON)
        ELSE()
            MESSAGE(SEND_ERROR "IPO is not supported: ${output}")
        ENDIF()
    ENDIF()
ENDFUNCTION()
